PATH_IMAGEN = "./models/checkpoint-601.pt"
PATH_OUTPUT = "./outputs"
PATH_INPUT = "./inputs"
PATH_TMP = "./tmp"
PATH_AUDIOFILE = "./test/test_audio.mp3"
PATH_FONT_EN="./data/fonts/HelveticaNeue.ttc"
PATH_FONT_JA="./data/fonts/A-OTF-GothicBBBPro-Medium.otf"
